export const projects = [
    {
      title: 'Pixexid',
      description: "This is a photo-sharing web application that allows you to search and download photos. It is collaboration project where developers can freely contribute to.",
        image: '/pixexid1.png',
        tags: ['Mongo', 'Express', 'NextJS', 'Node'],
      source: 'https://github.com/orgs/Pixexidv2/dashboard',
      visit: 'https://pixexid.com',
      id: 0,
    },
    {
      title: 'Amazon-Clone',
      description: "An Amazon-Clone where fakestore API is integrated. It uses Next Auth and Redux. The app is built in Next JS.",
        image: '/amazon-clone.png',
        tags: ['NextJS', 'Tailwind', 'API', 'Redux'],
      source: 'https://github.com/ClintZy101/Amazon-Nextjs-Tailwind',
      visit: 'https://amazon-nextjs-tailwind.vercel.app/',
      id: 2,
    },
    {
      title: 'Facebook-Clone',
      description:"A social media app where you can post photos from your local storage and post text stored in FIREBASE. It has basic facebook authentication.",
      image: '/hulu-clone.png',
      tags: ['Next JS', 'Firebase', 'Tailwind'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 1,
    },
  
    {
      title: 'Hulu-Clone',
      description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
      image: '/hulu-clone.png',
      tags: ['TMDB API', 'Next JS', 'Tailwind'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 3,
    },
    {
        title: 'Blog-it(Dev.To-Clone)',
        description: "This is a Blog App similar to Dev.To UI. It has basic CRUD functionalities and is connected to Firebase. It has also Authentication integration.",
        image: '/hulu-clone.png',
        tags: ['Next JS', 'Firebase', 'Redux'],
        source: 'https://google.com',
        visit: 'https://google.com',
        id: 3,
      },
      {
        title: 'Chattenger(Messenger-Clone)',
        description: "This is a simple group chat app where you type something and everybody sees your post. It also has basic Authentication.",
        image: '/amazon-clone.png',
        tags: ['Next JS', 'Next Auth', 'Firebase',],
        source: 'https://google.com',
        visit: 'https://google.com',
        id: 3,
      },
      {
        title: 'Twitter-Clone',
        description:"This is a Twitter-Clone app which has basic functionality to post a tweet and image url.",
        image: '/hulu-clone.png',
        tags: ['React JS', 'Firebase', 'Vanilla CSS'],
        source: 'https://google.com',
        visit: 'https://google.com',
        id: 1,
      },
  ];
  
  export const TimeLineData = [
    { year: 2017, text: 'Started my journey', },
    { year: 2018, text: 'Worked as a freelance developer', },
    { year: 2019, text: 'Founded JavaScript Mastery', },
    { year: 2020, text: 'Shared my projects with the world', },
    { year: 2021, text: 'Started my own platform', },
  ];